# @author haiyang.song
# @date 2018-11-6

version: '2'

services:
  orderer2.icdoit.com:
    image: hyperledger/fabric-orderer
    container_name: orderer2.icdoit.com
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=Org2MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_LONGINTERVAL=10s
      - ORDERER_KAFKA_RETRY_LONGTOTAL=100s
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_KAFKA_BROKERS=[k1:9092,k2:9092,k3:9092,k4:9092]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /opt/chainData/orderer/orderer2/:/var/hyperledger/production/ 
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block 
      - ../crypto-config/ordererOrganizations/icdoit.com/orderers/orderer2.icdoit.com/msp:/var/hyperledger/orderer/msp 
      - ../crypto-config/ordererOrganizations/icdoit.com/orderers/orderer2.icdoit.com/tls:/var/hyperledger/orderer/tls 
    ports:
      - 7050:7050 
    extra_hosts:
      - "z1:10.0.0.21"
      - "z2:10.0.0.22"
      - "z3:10.0.0.23"
      - "k1:10.0.0.21"
      - "k2:10.0.0.22"
      - "k3:10.0.0.23"
      - "k4:10.0.0.24"
      - "orderer1.icdoit.com:10.0.0.23"
      - "orderer2.icdoit.com:10.0.0.24"